# Generated by Django 4.2.3 on 2023-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='Phantome')),
                ('identifiant', models.TextField()),
                ('commentaire', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='Phantome')),
                ('identifiant', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('categorie', models.CharField(choices=[('web', 'web'), ('app', 'app'), ('ui', 'ui')], default='ui', max_length=20)),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('categorie', models.CharField(choices=[('web development', 'web development')], default='web development', max_length=20)),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
