# Generated by Django 4.1.4 on 2023-07-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='categorie',
            field=models.CharField(choices=[('ui', 'Infographie'), ('web', 'Design web'), ('app', 'Developpement web')], default='ui', max_length=20),
        ),
    ]
