# Generated by Django 4.2.3 on 2023-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_commentaire_commentaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
