# Generated by Django 4.2.3 on 2023-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_actualite_alter_commentaire_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='description',
            field=models.TextField(max_length=415),
        ),
    ]
