# Generated by Django 4.1.4 on 2023-08-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_actualite_image_alter_actualite_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('description', models.TextField(max_length=415)),
                ('date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.actualite')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
