# Generated by Django 4.1.4 on 2023-08-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_imageactualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='parto',
            field=models.TextField(default='Vector-Vision'),
        ),
    ]
